name: odoo_course
services:
  odoo:
    image: odoo:17.0
    restart: unless-stopped
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    environment:
      HOST: odoo_db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./addons:/mnt/extra-addons:ro
      - odoo-data:/var/lib/odoo
    command: --dev=reload

  odoo_db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  odoo-db-data:
